### ISSUE TITLE
Submit PR per: https://github.com/microsoft/vscode/issues/78013

### ISSUE THREAD

**Issue by HarjitSi** [russelldavis/vscode-better-pageup-pagedown#7]
Wondering if you submitted the PR: https://github.com/microsoft/vscode/issues/78013

Thanks.

**Comment by russelldavis** [comment]
I never got around to it, as I've been using Jetbrains stuff over VS Code lately. Maybe someday, or feel free to take a stab at it.

**Comment by HarjitSi** [comment]
Alas, I don't have the expertise. Thanks for the very quick response.
